@php
$user = auth()->user();
$so_id = $user->position->org_struct_id ?? null;
@endphp
@extends('layouts.app')
@section('title', $title)
@section('buttons-after') @endsection
@push('styles')
    <style>
        .select2-selection__rendered#select2-unitKerjaAsalCtrl-container {
            color: #3F4254 !important;
        }
    </style>
@endpush
@section('content')
    <form action="{{ route($route . '.store') }}" method="post">
        @csrf
        <div class="card card-custom">
            <div class="card-header">
                <h5 class="card-title">
                    Pengajuan Mutasi
                </h5>
                <button aria-label="Close" class="close" data-dismiss="card"
                    onclick="location.href='{{ route($route . '.index') }}'" type="button">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <div class="form-group row">
                            <label for="" class="col-4 text-bold">Unit Kerja Asal</label>
                            <div class="col-8 parent-group">
                                <select class="form-control base-plugin--select2" id="unitKerjaAsalCtrl"
                                    name="unit_kerja_asal" title="Unit Kerja Asal">
                                    <option></option>
                                    @if ($user->cekDivisiHC() )
                                        @foreach ($struct_tujuan as $key => $group)
                                            <optgroup
                                                label="{{ \Modules\Master\Entities\SO\OrgStruct::getLevelLabel($key) }}">
                                                @foreach ($group as $val)
                                                    <option value="{{ $val->id }}" @if($val->id == $user->position->struct->id) selected @endif>{{ $val->name }}</option>
                                                @endforeach
                                            </optgroup>
                                        @endforeach
                                    @else
                                        <option value="{{ $so_id }}">{{ $user->org_name }}</option>
                                    @endif
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-4 text-bold">Unit Kerja Tujuan</label>
                            <div class="col-8 parent-group">
                                <select class="form-control base-plugin--select2" id="unitKerjaTujuanCtrl"
                                    name="unit_kerja_tujuan" title="Unit Kerja Tujuan">
                                    <option></option>
                                    @foreach ($struct_tujuan as $key => $group)
                                        <optgroup label="{{ \Modules\Master\Entities\SO\OrgStruct::getLevelLabel($key) }}">
                                            @foreach ($group as $val)
                                                <option value="{{ $val->id }}">{{ $val->name }}</option>
                                            @endforeach
                                        </optgroup>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group row">
                            <label for="" class="col-4 col-form-label text-bold">Tgl Pengajuan</label>
                            <div class="col-8 parent-group">
                                <input type="text"  name="tgl_pengajuan"
                                    class="form-control base-plugin--datepicker tgl-pengajuan" data-language="en"
                                    data-format="dd/mm/yyyy"
                                    data-options='@json(['endDate' => now()->format('d/m/Y'), 'format' => 'dd/mm/yyyy'])' placeholder="{{ __('Tgl Pengajuan') }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-4 col-form-label text-bold">No. Surat</label>
                            <div class="col-8 parent-group">
                                <input class="form-control" disabled value="Generated By System">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="form-group row">
                            <label for="" class="col-2 col-form-label text-bold">Perihal</label>
                            <div class="col-10 parent-group">
                                <input type="text" name="perihal" class="form-control" placeholder="{{ __('Perihal') }}"
                                    value="Persetujuan Mutasi Tenaga Alih Daya">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="" class="col-2 col-form-label text-bold">Kepada</label>
                    <div class="col-10 parent-group">
                        <select name="to[]" id="" class="form-control base-plugin--select2-ajax"
                            title="Kepada" data-url="{{ route('settings.user.ajax.selectAjaxUserDivisiHC') }}">
                            <option value=""></option>
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="" class="col-2 text-bold">Surat Permohonan</label>
                    <div class="col-10 parent-group">
                        <div class="custom-file">
                            <input type="hidden" name="uploads[uploaded]" class="uploaded" value="">
                            <input type="file" multiple data-name="uploads" class="custom-file-input base-form--save-temp-files"
                                data-container="parent-group" data-max-size="2048" data-max-file="1" accept="*">
                            <label class="custom-file-label" for="file" style="color:#B5B5C3;font-weight:400;">{{ 'Pilih file' }}</label>
                        </div>
                        <div class="form-text text-muted">*Maksimal 2MB</div>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="" class="col-2 text-bold">Tembusan</label>
                    <div class="col-10 parent-group">
                        <select name="user_id[]" id="" multiple class="form-control base-plugin--select2-ajax"
                            title="Jabatan" data-url="{{ route('settings.user.ajax.selectAjaxUserDivisiHC') }}">
                            <option value=""></option>
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="" class="col-2 col-form-label text-bold">Menunjuk</label>
                    <div class="col-10 parent-group">
                        <textarea name="menunjuk" class="base-plugin--summernote-2" data-height="200"
                            placeholder="{{ __('menunjuk') }}"></textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="" class="col-2 col-form-label text-bold">Menindaklanjuti</label>
                    <div class="col-10 parent-group">
                        <textarea name="menindaklanjuti" class="form-control base-plugin--summernote-2" data-height="200"
                            placeholder="{{ __('Menindaklanjuti') }}"></textarea>
                    </div>
                </div>
                <hr class="my-8">
                <div id="requirement-row">
                    <div class="form-row justify-content-left">
                        <div class="form-group col-3">
                            <label for="">Posisi TAD</label>
                            <select name="pegawai[0][jabatan_id]" class="form-control base-plugin--select2 jabatan-ctrl"
                                id="jabatan0Ctrl" data-placeholder="Posisi TAD">
                                <option value=""></option>
                                @foreach ($POSISI_TAD as $item)
                                    <option value="{{ $item->idunit }}">{{ $item->NM_UNIT }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-3">
                            <label for="">Personil TAD</label>
                            <select class="form-control base-plugin--select2 personil-ctrl"
                                data-placeholder="Personil TAD" id="personil0Ctrl"
                                name="pegawai[0][id]" onchange="selectNio(this)">
                                <option value=""></option>
                            </select>
                        </div>
                        <div class="form-group col-2">
                            <label for="">Tgl SK Mutasi</label>
                            <input class="form-control base-plugin--datepicker tgl-mutasi-ctrl"
                                id="tglMutasi0Ctrl"
                                data-language="en"
                                data-format="dd/mm/yyyy" data-options='@json(['startDate' => now(), 'format' => 'dd/mm/yyyy'])'
                                name="pegawai[0][tanggal_mutasi]" placeholder="Tgl SK Mutasi">
                        </div>
                        <div class="form-group col-2">
                            <label for="">Tgl Efektif</label>
                            <input class="form-control base-plugin--datepicker tgl-efektif-ctrl"
                                id="tglEfektif0Ctrl"
                                data-language="en"
                                data-format="dd/mm/yyyy" data-options='@json(['startDate' => now(), 'format' => 'dd/mm/yyyy'])'
                                name="pegawai[0][tanggal_efektif]" placeholder="Tgl Efektif">
                        </div>
                        <div class="form-group col-1">
                            <label for="">&nbsp;</label>
                            <button class="btn btn-icon btn-primary btn-circle btn-add-requirement"
                                onclick="addRow(this)" type="button">
                                <i class="fas fa-plus"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-6">
                @include('pengajuan::mutasi.partials.flow')
            </div>
            <div class="col-6">
                <div class="card card-custom gutter-b" style="margin-bottom:0; height:100%;">
                    <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between p-4 flex-lg-wrap flex-xl-nowrap">
                            <div class="d-flex flex-column mr-5">
                                <a href="#" class="h4 text-dark text-hover-primary mb-5">
                                    Informasi
                                </a>
                                <p class="text-dark-50">
                                    Sebelum submit pastikan data Pengajuan Mutasi tersebut sudah sesuai.
                                </p>
                            </div>
                            <div class="ml-6 ml-lg-0 ml-xxl-6 flex-shrink-0">
                                @php
                                    $menu = \Modules\Settings\Entities\Menu::where('code', $module)->first();
                                    $count = $menu->flows()->count();
                                    $submit = $count == 0 ? 'disabled' : 'enabled';
                                @endphp
                                <x-btn-draft via="base-form--submit-page" submit="{{ $submit }}" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <template id="requirement-form">
        <div class="form-row justify-content-left">
            <div class="form-group col-3">
                <select name="pegawai[@{{:index}}][jabatan_id]"
                    class="form-control base-plugin--select2 jabatan-ctrl" data-placeholder="Posisi TAD">
                    <option value=""></option>
                    @foreach ($POSISI_TAD as $item)
                        <option value="{{ $item->idunit }}">{{ $item->NM_UNIT }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group col-3">
                <select name="pegawai[@{{:index}}][id]" onchange="selectNio(this)"
                    class="form-control base-plugin--select2 personil-ctrl" data-placeholder="Personil TAD">
                    <option value=""></option>
                </select>
            </div>
            <div class="form-group col-2">
                <input class="form-control base-plugin--datepicker tgl-mutasi-ctrl"
                    data-language="en"
                    data-format="dd/mm/yyyy" data-options='@json(['startDate' => now(), 'format' => 'dd/mm/yyyy'])'
                    name="pegawai[@{{:index}}][tanggal_mutasi]" placeholder="Tgl SK Mutasi">
            </div>
            <div class="form-group col-2">
                <input class="form-control base-plugin--datepicker tgl-efektif-ctrl"
                    data-language="en"
                    data-format="dd/mm/yyyy" data-options='@json(['startDate' => now(), 'format' => 'dd/mm/yyyy'])'
                    name="pegawai[@{{:index}}][tanggal_efektif]" placeholder="Tgl Efektif">
            </div>
            <div class="form-group col-1">
                <a href="javascript:;" onclick="deleteRow(this)" class="btn btn-icon btn-danger btn-circle"><i
                        class="fas fa-trash"></i></a>
            </div>
        </div>
    </template>
@endsection

@push('scripts')
    <script>
        addRow = (elem) => {
            var row = $('#requirement-form').html();
            var index = $('.form-row:last').index();
            var tmpl = jsrender.templates(row);
            var resp = {
                'index': index + 1
            };
            var dom = tmpl.render(resp);
            $('#requirement-row').append(dom);
            console.log(resp);

            BasePlugin.initSelect2();
            BasePlugin.initDatepicker();
        }
        deleteRow = (elem) => {
            $(elem).parent().parent().remove();
            BasePlugin.initSelect2();
        }

        function countRow() {
            return $('.form-row:last').index()+1;
        }

        function selectNio(nio) {
            var totalNioSelected = $('select.personil-ctrl option:selected[value="' + nio.value + '"]').length;
            if (nio.value != '' && totalNioSelected > 1) {
                $.gritter.add({
                    title: 'Failed!',
                    text: 'Personil sudah di pilih!',
                    image: baseurl + '/assets/images/icon/ui/cross.png',
                    sticky: false,
                    time: '3000'
                });
                console.log($(nio).val());
                $(nio).val('').trigger('change');
            }
        }

        function unitKerjaAsalChanged(exists = false) {
            if (exists) {
                $('select.jabatan-ctrl').prop('disabled', false);
                $('select.personil-ctrl').prop('disabled', false);
                $('.tgl-mutasi-ctrl').prop('disabled', false);
                $('.btn-add-requirement').prop('disabled', false);
            } else {
                // $('select.jabatan-ctrl').prop('disabled', true);
                // $('select.personil-ctrl').prop('disabled', true);
                // $('.tgl-mutasi-ctrl').prop('disabled', true);
                // $('.btn-add-requirement').prop('disabled', true);
            }
        }

        let unitKerjaAsal;
        let unitKerjaAsalText;
        $(document).ready(function() {
            unitKerjaAsalChanged();
            $(document)
                .on('change', '#unitKerjaAsalCtrl', function(){
                    let unitKerjaAsalCtrl   = $('#unitKerjaAsalCtrl');
                    unitKerjaAsal           = unitKerjaAsalCtrl.val();
                    unitKerjaAsalText       = unitKerjaAsalCtrl.find('option:selected').text();
                    unitKerjaAsalChanged(Boolean(unitKerjaAsal));
                    $('#jabatan0Ctrl, .jabatan-ctrl').val('').change();
                    $('#personil0Ctrl, .personil-ctrl').val('').change();
                    $('#tglMutasi0Ctrl, .tgl-mutasi-ctrl').val('').change();

                    // ajax
                    let jabatan_id      = $('.jabatan-ctrl').val();
                    let personilCtrl    = $('.jabatan-ctrl').parent().parent().find('.personil-ctrl');
                    $.ajax({
                        method: 'GET',
                        url: '{{ route('personil.migrasi.getAjaxResignMutasi') }}',
                        data: {
                            jabatan_id: jabatan_id,
                            so_id:      unitKerjaAsal,
                            form_type: 'mutasi',
                        },
                        success: function(response, state, xhr) {
                            let options = `<option value='' selected disabled></option>`;
                            // let options = ``;
                            for (let item of response) {
                                options += `<option value='${item.id}'>${item.nama} (${item.kepegawaian.nio})</option>`;
                            }
                            personilCtrl.select2('destroy');
                            personilCtrl.html(options);
                            personilCtrl.select2();
                        },
                        error: function(a, b, c) {
                            console.log(a, b, c);
                        }
                    });
                })
                .on('change', '.jabatan-ctrl', function() {
                    let jabatan_id      = $(this).val();
                    let personilCtrl    = $(this).parent().parent().find('.personil-ctrl');
                    console.log(176, personilCtrl);
                    $.ajax({
                        method: 'GET',
                        url: '{{ route('personil.migrasi.getAjaxResignMutasi') }}',
                        data: {
                            jabatan_id: jabatan_id,
                            so_id:      unitKerjaAsal,
                            form_type: 'mutasi',
                        },
                        success: function(response, state, xhr) {
                            let options = `<option value='' selected disabled></option>`;
                            // let options = ``;
                            for (let item of response) {
                                options += `<option value='${item.id}'>${item.nama} (${item.kepegawaian.nio})</option>`;
                            }
                            personilCtrl.select2('destroy');
                            personilCtrl.html(options);
                            personilCtrl.select2();
                        },
                        error: function(a, b, c) {
                            console.log(a, b, c);
                        }
                    });
                });
        });
    </script>
@endpush
