@extends('layouts.app')
@section('title', $title)
@section('buttons') @endsection
@section('content')
    <form action="{{ route($route . '.store') }}" method="post">
        @csrf
        <div class="card card-custom">
            <div class="card-body">
                <div class="form-group row">
                    <label for="" class="col-2 text-bold">Unit Kerja</label>
                    <label for="" class="col">: {{ auth()->user()->cabang }}</label>
                </div>
                <div class="form-group row">
                    <label for="" class="col-2 text-bold">Tanggal Pengajuan</label>
                    <label for="" class="col">: {{ \Carbon\Carbon::now()->format('d/m/Y') }}</label>
                </div>
                <div class="form-group row">
                    <label for="" class="col-2 text-bold">Nomor Tiket</label>
                    <label for="" class="col font-italic">: Generated By System</label>
                </div>

                <div class="form-group row">
                    <label for="" class="col-2 text-bold">Lampirkan Surat Permohonan</label>
                    <div class="col-4">
                        <div class="custom-file">
                            <input type="file" name="surat" accept=".pdf" class="custom-file-input" size="2048" />
                            <label class="custom-file-label" for="file" style="color:#B5B5C3;font-weight:400;">Pilih file</label>
                            <span class="form-text text-muted">Lampirkan File Surat Permohonan dengan format .pdf dan ukuran
                                maksimal 2 Mb</span>
                        </div>
                    </div>
                </div>
                <hr class="my-8">
                <div id="requirement-row">
                    <div class="form-row justify-content-center">
                        <div class="form-group col-3">
                            <label for="">Nama TAD</label>
                            <select name="tad_id[0]" id="" class="form-control base-plugin--select2">
                                <option value=""></option>
                            </select>
                        </div>
                        <div class="form-group col-2">
                            <label for="">Tanggal Resign</label>
                            <input type="text" name="resign_at[0]" class="form-control base-plugin--datepicker"
                                data-format="dd/mm/yyyy"
                                data-language="en" placeholder="Tanggal Resign">
                        </div>
                        <div class="form-group col-1">
                            <label for="">&nbsp;</label>
                            <a href="javascript:;" onclick="addRow(this)" class="btn btn-icon btn-primary btn-circle"><i
                                    class="fas fa-plus"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer p-5">
                <div class="float-right d-flex flex-row">
                    <x-btn-back class="mr-2" url="{{ route($route . '.index') }}" />
                    <x-btn-save via="base-form--submit-page" />
                </div>
            </div>
        </div>
    </form>

    <template id="requirement-form">
        <div class="form-row justify-content-center">
            <div class="form-group col-3">
                <label for="">Nama TAD</label>
                <select name="tad_id[@{{:index}}]" id="" class="form-control base-plugin--select2">
                    <option value=""></option>
                </select>
            </div>
            <div class="form-group col-2">
                <label for="">Tanggal Resign</label>
                <input type="text" name="resign_at[@{{:index}}]" class="form-control base-plugin--datepicker"
                    data-format="dd/mm/yyyy"
                    data-language="en" placeholder="Tanggal Resign">
            </div>
            <div class="form-group col-1">
                <label for="">&nbsp;</label>
                <a href="javascript:;" onclick="deleteRow(this)" class="btn btn-icon btn-danger btn-circle"><i
                        class="fas fa-trash"></i></a>
            </div>
        </div>
    </template>
@endsection
@push('scripts')
    <script>
        addRow = (elem) => {
            var row = $('#requirement-form').html();
            var index = $('.form-row:last').index();
            var tmpl = jsrender.templates(row);
            var resp = {
                'index': index + 1
            };
            var dom = tmpl.render(resp);
            $('#requirement-row').append(dom);
            console.log(resp);
            BasePlugin.initSelect2();
        }
        deleteRow = (elem) => {
            $(elem).parent().parent().remove();
            BasePlugin.initSelect2();
        }
    </script>
@endpush
