<?php

namespace Modules\Master\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Master\Entities\Kota;
use Modules\Master\Entities\Provinsi;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    $data = [
    ["id" => 1101, "id_provinsi" => 11, "kabupaten" => "Kab. Simeulue"],
    ["id" => 1102, "id_provinsi" => 11, "kabupaten" => "Kab. Aceh Singkil"],
    ["id" => 1103, "id_provinsi" => 11, "kabupaten" => "Kab. Aceh Selatan"],
    ["id" => 1104, "id_provinsi" => 11, "kabupaten" => "Kab. Aceh Tenggara"],
    ["id" => 1105, "id_provinsi" => 11, "kabupaten" => "Kab. Aceh Timur"],
    ["id" => 1106, "id_provinsi" => 11, "kabupaten" => "Kab. Aceh Tengah"],
    ["id" => 1107, "id_provinsi" => 11, "kabupaten" => "Kab. Aceh Barat"],
    ["id" => 1108, "id_provinsi" => 11, "kabupaten" => "Kab. Aceh Besar"],
    ["id" => 1109, "id_provinsi" => 11, "kabupaten" => "Kab. Pidie"],
    ["id" => 1110, "id_provinsi" => 11, "kabupaten" => "Kab. Bireuen"],
    ["id" => 1111, "id_provinsi" => 11, "kabupaten" => "Kab. Aceh Utara"],
    ["id" => 1112, "id_provinsi" => 11, "kabupaten" => "Kab. Aceh Barat Daya"],
    ["id" => 1113, "id_provinsi" => 11, "kabupaten" => "Kab. Gayo Lues"],
    ["id" => 1114, "id_provinsi" => 11, "kabupaten" => "Kab. Aceh Tamiang"],
    ["id" => 1115, "id_provinsi" => 11, "kabupaten" => "Kab. Nagan Raya"],
    ["id" => 1116, "id_provinsi" => 11, "kabupaten" => "Kab. Aceh Jaya"],
    ["id" => 1117, "id_provinsi" => 11, "kabupaten" => "Kab. Bener Meriah"],
    ["id" => 1118, "id_provinsi" => 11, "kabupaten" => "Kab. Pidie Jaya"],
    ["id" => 1171, "id_provinsi" => 11, "kabupaten" => "Kota Banda Aceh"],
    ["id" => 1172, "id_provinsi" => 11, "kabupaten" => "Kota Sabang"],
    ["id" => 1173, "id_provinsi" => 11, "kabupaten" => "Kota Langsa"],
    ["id" => 1174, "id_provinsi" => 11, "kabupaten" => "Kota Lhokseumawe"],
    ["id" => 1175, "id_provinsi" => 11, "kabupaten" => "Kota Subulussalam"],
    ["id" => 1201, "id_provinsi" => 12, "kabupaten" => "Kab. Nias"],
    ["id" => 1202, "id_provinsi" => 12, "kabupaten" => "Kab. Mandailing Natal"],
    ["id" => 1203, "id_provinsi" => 12, "kabupaten" => "Kab. Tapanuli Selatan"],
    ["id" => 1204, "id_provinsi" => 12, "kabupaten" => "Kab. Tapanuli Tengah"],
    ["id" => 1205, "id_provinsi" => 12, "kabupaten" => "Kab. Tapanuli Utara"],
    ["id" => 1206, "id_provinsi" => 12, "kabupaten" => "Kab. Toba Samosir"],
    ["id" => 1207, "id_provinsi" => 12, "kabupaten" => "Kab. Labuhan Batu"],
    ["id" => 1208, "id_provinsi" => 12, "kabupaten" => "Kab. Asahan"],
    ["id" => 1209, "id_provinsi" => 12, "kabupaten" => "Kab. Simalungun"],
    ["id" => 1210, "id_provinsi" => 12, "kabupaten" => "Kab. Dairi"],
    ["id" => 1211, "id_provinsi" => 12, "kabupaten" => "Kab. Karo"],
    ["id" => 1212, "id_provinsi" => 12, "kabupaten" => "Kab. Deli Serdang"],
    ["id" => 1213, "id_provinsi" => 12, "kabupaten" => "Kab. Langkat"],
    ["id" => 1214, "id_provinsi" => 12, "kabupaten" => "Kab. Nias Selatan"],
    [
        "id" => 1215,
        "id_provinsi" => 12,
        "kabupaten" => "Kab. Humbang Hasundutan",
    ],
    ["id" => 1216, "id_provinsi" => 12, "kabupaten" => "Kab. Pakpak Bharat"],
    ["id" => 1217, "id_provinsi" => 12, "kabupaten" => "Kab. Samosir"],
    ["id" => 1218, "id_provinsi" => 12, "kabupaten" => "Kab. Serdang Bedagai"],
    ["id" => 1219, "id_provinsi" => 12, "kabupaten" => "Kab. Batu Bara"],
    [
        "id" => 1220,
        "id_provinsi" => 12,
        "kabupaten" => "Kab. Padang Lawas Utara",
    ],
    ["id" => 1221, "id_provinsi" => 12, "kabupaten" => "Kab. Padang Lawas"],
    [
        "id" => 1222,
        "id_provinsi" => 12,
        "kabupaten" => "Kab. Labuhan Batu Selatan",
    ],
    [
        "id" => 1223,
        "id_provinsi" => 12,
        "kabupaten" => "Kab. Labuhan Batu Utara",
    ],
    ["id" => 1224, "id_provinsi" => 12, "kabupaten" => "Kab. Nias Utara"],
    ["id" => 1225, "id_provinsi" => 12, "kabupaten" => "Kab. Nias Barat"],
    ["id" => 1271, "id_provinsi" => 12, "kabupaten" => "Kota Sibolga"],
    ["id" => 1272, "id_provinsi" => 12, "kabupaten" => "Kota Tanjung Balai"],
    ["id" => 1273, "id_provinsi" => 12, "kabupaten" => "Kota Pematang Siantar"],
    ["id" => 1274, "id_provinsi" => 12, "kabupaten" => "Kota Tebing Tinggi"],
    ["id" => 1275, "id_provinsi" => 12, "kabupaten" => "Kota Medan"],
    ["id" => 1276, "id_provinsi" => 12, "kabupaten" => "Kota Binjai"],
    ["id" => 1277, "id_provinsi" => 12, "kabupaten" => "Kota Padangsidimpuan"],
    ["id" => 1278, "id_provinsi" => 12, "kabupaten" => "Kota Gunungsitoli"],
    [
        "id" => 1301,
        "id_provinsi" => 13,
        "kabupaten" => "Kab. Kepulauan Mentawai",
    ],
    ["id" => 1302, "id_provinsi" => 13, "kabupaten" => "Kab. Pesisir Selatan"],
    ["id" => 1303, "id_provinsi" => 13, "kabupaten" => "Kab. Solok"],
    ["id" => 1304, "id_provinsi" => 13, "kabupaten" => "Kab. Sijunjung"],
    ["id" => 1305, "id_provinsi" => 13, "kabupaten" => "Kab. Tanah Datar"],
    ["id" => 1306, "id_provinsi" => 13, "kabupaten" => "Kab. Padang Pariaman"],
    ["id" => 1307, "id_provinsi" => 13, "kabupaten" => "Kab. Agam"],
    ["id" => 1308, "id_provinsi" => 13, "kabupaten" => "Kab. Lima Puluh Kota"],
    ["id" => 1309, "id_provinsi" => 13, "kabupaten" => "Kab. Pasaman"],
    ["id" => 1310, "id_provinsi" => 13, "kabupaten" => "Kab. Solok Selatan"],
    ["id" => 1311, "id_provinsi" => 13, "kabupaten" => "Kab. Dharmasraya"],
    ["id" => 1312, "id_provinsi" => 13, "kabupaten" => "Kab. Pasaman Barat"],
    ["id" => 1371, "id_provinsi" => 13, "kabupaten" => "Kota Padang"],
    ["id" => 1372, "id_provinsi" => 13, "kabupaten" => "Kota Solok"],
    ["id" => 1373, "id_provinsi" => 13, "kabupaten" => "Kota Sawah Lunto"],
    ["id" => 1374, "id_provinsi" => 13, "kabupaten" => "Kota Padang Panjang"],
    ["id" => 1375, "id_provinsi" => 13, "kabupaten" => "Kota Bukittinggi"],
    ["id" => 1376, "id_provinsi" => 13, "kabupaten" => "Kota Payakumbuh"],
    ["id" => 1377, "id_provinsi" => 13, "kabupaten" => "Kota Pariaman"],
    ["id" => 1401, "id_provinsi" => 14, "kabupaten" => "Kab. Kuantan Singingi"],
    ["id" => 1402, "id_provinsi" => 14, "kabupaten" => "Kab. Indragiri Hulu"],
    ["id" => 1403, "id_provinsi" => 14, "kabupaten" => "Kab. Indragiri Hilir"],
    ["id" => 1404, "id_provinsi" => 14, "kabupaten" => "Kab. Pelalawan"],
    ["id" => 1405, "id_provinsi" => 14, "kabupaten" => "Kab. S I A K"],
    ["id" => 1406, "id_provinsi" => 14, "kabupaten" => "Kab. Kampar"],
    ["id" => 1407, "id_provinsi" => 14, "kabupaten" => "Kab. Rokan Hulu"],
    ["id" => 1408, "id_provinsi" => 14, "kabupaten" => "Kab. Bengkalis"],
    ["id" => 1409, "id_provinsi" => 14, "kabupaten" => "Kab. Rokan Hilir"],
    [
        "id" => 1410,
        "id_provinsi" => 14,
        "kabupaten" => "Kab. Kepulauan Meranti",
    ],
    ["id" => 1471, "id_provinsi" => 14, "kabupaten" => "Kota Pekanbaru"],
    ["id" => 1473, "id_provinsi" => 14, "kabupaten" => "Kota D U M A I"],
    ["id" => 1501, "id_provinsi" => 15, "kabupaten" => "Kab. Kerinci"],
    ["id" => 1502, "id_provinsi" => 15, "kabupaten" => "Kab. Merangin"],
    ["id" => 1503, "id_provinsi" => 15, "kabupaten" => "Kab. Sarolangun"],
    ["id" => 1504, "id_provinsi" => 15, "kabupaten" => "Kab. Batang Hari"],
    ["id" => 1505, "id_provinsi" => 15, "kabupaten" => "Kab. Muaro Jambi"],
    [
        "id" => 1506,
        "id_provinsi" => 15,
        "kabupaten" => "Kab. Tanjung Jabung Timur",
    ],
    [
        "id" => 1507,
        "id_provinsi" => 15,
        "kabupaten" => "Kab. Tanjung Jabung Barat",
    ],
    ["id" => 1508, "id_provinsi" => 15, "kabupaten" => "Kab. Tebo"],
    ["id" => 1509, "id_provinsi" => 15, "kabupaten" => "Kab. Bungo"],
    ["id" => 1571, "id_provinsi" => 15, "kabupaten" => "Kota Jambi"],
    ["id" => 1572, "id_provinsi" => 15, "kabupaten" => "Kota Sungai Penuh"],
    [
        "id" => 1601,
        "id_provinsi" => 16,
        "kabupaten" => "Kab. Ogan Komering Ulu",
    ],
    [
        "id" => 1602,
        "id_provinsi" => 16,
        "kabupaten" => "Kab. Ogan Komering Ilir",
    ],
    ["id" => 1603, "id_provinsi" => 16, "kabupaten" => "Kab. Muara Enim"],
    ["id" => 1604, "id_provinsi" => 16, "kabupaten" => "Kab. Lahat"],
    ["id" => 1605, "id_provinsi" => 16, "kabupaten" => "Kab. Musi Rawas"],
    ["id" => 1606, "id_provinsi" => 16, "kabupaten" => "Kab. Musi Banyuasin"],
    ["id" => 1607, "id_provinsi" => 16, "kabupaten" => "Kab. Banyu Asin"],
    [
        "id" => 1608,
        "id_provinsi" => 16,
        "kabupaten" => "Kab. Ogan Komering Ulu Selatan",
    ],
    [
        "id" => 1609,
        "id_provinsi" => 16,
        "kabupaten" => "Kab. Ogan Komering Ulu Timur",
    ],
    ["id" => 1610, "id_provinsi" => 16, "kabupaten" => "Kab. Ogan Ilir"],
    ["id" => 1611, "id_provinsi" => 16, "kabupaten" => "Kab. Empat Lawang"],
    ["id" => 1671, "id_provinsi" => 16, "kabupaten" => "Kota Palembang"],
    ["id" => 1672, "id_provinsi" => 16, "kabupaten" => "Kota Prabumulih"],
    ["id" => 1673, "id_provinsi" => 16, "kabupaten" => "Kota Pagar Alam"],
    ["id" => 1674, "id_provinsi" => 16, "kabupaten" => "Kota Lubuklinggau"],
    ["id" => 1701, "id_provinsi" => 17, "kabupaten" => "Kab. Bengkulu Selatan"],
    ["id" => 1702, "id_provinsi" => 17, "kabupaten" => "Kab. Rejang Lebong"],
    ["id" => 1703, "id_provinsi" => 17, "kabupaten" => "Kab. Bengkulu Utara"],
    ["id" => 1704, "id_provinsi" => 17, "kabupaten" => "Kab. Kaur"],
    ["id" => 1705, "id_provinsi" => 17, "kabupaten" => "Kab. Seluma"],
    ["id" => 1706, "id_provinsi" => 17, "kabupaten" => "Kab. Mukomuko"],
    ["id" => 1707, "id_provinsi" => 17, "kabupaten" => "Kab. Lebong"],
    ["id" => 1708, "id_provinsi" => 17, "kabupaten" => "Kab. Kepahiang"],
    ["id" => 1709, "id_provinsi" => 17, "kabupaten" => "Kab. Bengkulu Tengah"],
    ["id" => 1771, "id_provinsi" => 17, "kabupaten" => "Kota Bengkulu"],
    ["id" => 1801, "id_provinsi" => 18, "kabupaten" => "Kab. Lampung Barat"],
    ["id" => 1802, "id_provinsi" => 18, "kabupaten" => "Kab. Tanggamus"],
    ["id" => 1803, "id_provinsi" => 18, "kabupaten" => "Kab. Lampung Selatan"],
    ["id" => 1804, "id_provinsi" => 18, "kabupaten" => "Kab. Lampung Timur"],
    ["id" => 1805, "id_provinsi" => 18, "kabupaten" => "Kab. Lampung Tengah"],
    ["id" => 1806, "id_provinsi" => 18, "kabupaten" => "Kab. Lampung Utara"],
    ["id" => 1807, "id_provinsi" => 18, "kabupaten" => "Kab. Way Kanan"],
    ["id" => 1808, "id_provinsi" => 18, "kabupaten" => "Kab. Tulangbawang"],
    ["id" => 1809, "id_provinsi" => 18, "kabupaten" => "Kab. Pesawaran"],
    ["id" => 1810, "id_provinsi" => 18, "kabupaten" => "Kab. Pringsewu"],
    ["id" => 1811, "id_provinsi" => 18, "kabupaten" => "Kab. Mesuji"],
    [
        "id" => 1812,
        "id_provinsi" => 18,
        "kabupaten" => "Kab. Tulang Bawang Barat",
    ],
    ["id" => 1813, "id_provinsi" => 18, "kabupaten" => "Kab. Pesisir Barat"],
    ["id" => 1871, "id_provinsi" => 18, "kabupaten" => "Kota Bandar Lampung"],
    ["id" => 1872, "id_provinsi" => 18, "kabupaten" => "Kota Metro"],
    ["id" => 1901, "id_provinsi" => 19, "kabupaten" => "Kab. Bangka"],
    ["id" => 1902, "id_provinsi" => 19, "kabupaten" => "Kab. Belitung"],
    ["id" => 1903, "id_provinsi" => 19, "kabupaten" => "Kab. Bangka Barat"],
    ["id" => 1904, "id_provinsi" => 19, "kabupaten" => "Kab. Bangka Tengah"],
    ["id" => 1905, "id_provinsi" => 19, "kabupaten" => "Kab. Bangka Selatan"],
    ["id" => 1906, "id_provinsi" => 19, "kabupaten" => "Kab. Belitung Timur"],
    ["id" => 1971, "id_provinsi" => 19, "kabupaten" => "Kota Pangkal Pinang"],
    ["id" => 2101, "id_provinsi" => 21, "kabupaten" => "Kab. Karimun"],
    ["id" => 2102, "id_provinsi" => 21, "kabupaten" => "Kab. Bintan"],
    ["id" => 2103, "id_provinsi" => 21, "kabupaten" => "Kab. Natuna"],
    ["id" => 2104, "id_provinsi" => 21, "kabupaten" => "Kab. Lingga"],
    [
        "id" => 2105,
        "id_provinsi" => 21,
        "kabupaten" => "Kab. Kepulauan Anambas",
    ],
    ["id" => 2171, "id_provinsi" => 21, "kabupaten" => "Kota B A T A M"],
    ["id" => 2172, "id_provinsi" => 21, "kabupaten" => "Kota Tanjung Pinang"],
    ["id" => 3101, "id_provinsi" => 31, "kabupaten" => "Kab. Kepulauan Seribu"],
    ["id" => 3171, "id_provinsi" => 31, "kabupaten" => "Kota Jakarta Selatan"],
    ["id" => 3172, "id_provinsi" => 31, "kabupaten" => "Kota Jakarta Timur"],
    ["id" => 3173, "id_provinsi" => 31, "kabupaten" => "Kota Jakarta Pusat"],
    ["id" => 3174, "id_provinsi" => 31, "kabupaten" => "Kota Jakarta Barat"],
    ["id" => 3175, "id_provinsi" => 31, "kabupaten" => "Kota Jakarta Utara"],
    ["id" => 3201, "id_provinsi" => 32, "kabupaten" => "Kab. Bogor"],
    ["id" => 3202, "id_provinsi" => 32, "kabupaten" => "Kab. Sukabumi"],
    ["id" => 3203, "id_provinsi" => 32, "kabupaten" => "Kab. Cianjur"],
    ["id" => 3204, "id_provinsi" => 32, "kabupaten" => "Kab. Bandung"],
    ["id" => 3205, "id_provinsi" => 32, "kabupaten" => "Kab. Garut"],
    ["id" => 3206, "id_provinsi" => 32, "kabupaten" => "Kab. Tasikmalaya"],
    ["id" => 3207, "id_provinsi" => 32, "kabupaten" => "Kab. Ciamis"],
    ["id" => 3208, "id_provinsi" => 32, "kabupaten" => "Kab. Kuningan"],
    ["id" => 3209, "id_provinsi" => 32, "kabupaten" => "Kab. Cirebon"],
    ["id" => 3210, "id_provinsi" => 32, "kabupaten" => "Kab. Majalengka"],
    ["id" => 3211, "id_provinsi" => 32, "kabupaten" => "Kab. Sumedang"],
    ["id" => 3212, "id_provinsi" => 32, "kabupaten" => "Kab. Indramayu"],
    ["id" => 3213, "id_provinsi" => 32, "kabupaten" => "Kab. Subang"],
    ["id" => 3214, "id_provinsi" => 32, "kabupaten" => "Kab. Purwakarta"],
    ["id" => 3215, "id_provinsi" => 32, "kabupaten" => "Kab. Karawang"],
    ["id" => 3216, "id_provinsi" => 32, "kabupaten" => "Kab. Bekasi"],
    ["id" => 3217, "id_provinsi" => 32, "kabupaten" => "Kab. Bandung Barat"],
    ["id" => 3218, "id_provinsi" => 32, "kabupaten" => "Kab. Pangandaran"],
    ["id" => 3271, "id_provinsi" => 32, "kabupaten" => "Kota Bogor"],
    ["id" => 3272, "id_provinsi" => 32, "kabupaten" => "Kota Sukabumi"],
    ["id" => 3273, "id_provinsi" => 32, "kabupaten" => "Kota Bandung"],
    ["id" => 3274, "id_provinsi" => 32, "kabupaten" => "Kota Cirebon"],
    ["id" => 3275, "id_provinsi" => 32, "kabupaten" => "Kota Bekasi"],
    ["id" => 3276, "id_provinsi" => 32, "kabupaten" => "Kota Depok"],
    ["id" => 3277, "id_provinsi" => 32, "kabupaten" => "Kota Cimahi"],
    ["id" => 3278, "id_provinsi" => 32, "kabupaten" => "Kota Tasikmalaya"],
    ["id" => 3279, "id_provinsi" => 32, "kabupaten" => "Kota Banjar"],
    ["id" => 3301, "id_provinsi" => 33, "kabupaten" => "Kab. Cilacap"],
    ["id" => 3302, "id_provinsi" => 33, "kabupaten" => "Kab. Banyumas"],
    ["id" => 3303, "id_provinsi" => 33, "kabupaten" => "Kab. Purbalingga"],
    ["id" => 3304, "id_provinsi" => 33, "kabupaten" => "Kab. Banjarnegara"],
    ["id" => 3305, "id_provinsi" => 33, "kabupaten" => "Kab. Kebumen"],
    ["id" => 3306, "id_provinsi" => 33, "kabupaten" => "Kab. Purworejo"],
    ["id" => 3307, "id_provinsi" => 33, "kabupaten" => "Kab. Wonosobo"],
    ["id" => 3308, "id_provinsi" => 33, "kabupaten" => "Kab. Magelang"],
    ["id" => 3309, "id_provinsi" => 33, "kabupaten" => "Kab. Boyolali"],
    ["id" => 3310, "id_provinsi" => 33, "kabupaten" => "Kab. Klaten"],
    ["id" => 3311, "id_provinsi" => 33, "kabupaten" => "Kab. Sukoharjo"],
    ["id" => 3312, "id_provinsi" => 33, "kabupaten" => "Kab. Wonogiri"],
    ["id" => 3313, "id_provinsi" => 33, "kabupaten" => "Kab. Karanganyar"],
    ["id" => 3314, "id_provinsi" => 33, "kabupaten" => "Kab. Sragen"],
    ["id" => 3315, "id_provinsi" => 33, "kabupaten" => "Kab. Grobogan"],
    ["id" => 3316, "id_provinsi" => 33, "kabupaten" => "Kab. Blora"],
    ["id" => 3317, "id_provinsi" => 33, "kabupaten" => "Kab. Rembang"],
    ["id" => 3318, "id_provinsi" => 33, "kabupaten" => "Kab. Pati"],
    ["id" => 3319, "id_provinsi" => 33, "kabupaten" => "Kab. Kudus"],
    ["id" => 3320, "id_provinsi" => 33, "kabupaten" => "Kab. Jepara"],
    ["id" => 3321, "id_provinsi" => 33, "kabupaten" => "Kab. Demak"],
    ["id" => 3322, "id_provinsi" => 33, "kabupaten" => "Kab. Semarang"],
    ["id" => 3323, "id_provinsi" => 33, "kabupaten" => "Kab. Temanggung"],
    ["id" => 3324, "id_provinsi" => 33, "kabupaten" => "Kab. Kendal"],
    ["id" => 3325, "id_provinsi" => 33, "kabupaten" => "Kab. Batang"],
    ["id" => 3326, "id_provinsi" => 33, "kabupaten" => "Kab. Pekalongan"],
    ["id" => 3327, "id_provinsi" => 33, "kabupaten" => "Kab. Pemalang"],
    ["id" => 3328, "id_provinsi" => 33, "kabupaten" => "Kab. Tegal"],
    ["id" => 3329, "id_provinsi" => 33, "kabupaten" => "Kab. Brebes"],
    ["id" => 3371, "id_provinsi" => 33, "kabupaten" => "Kota Magelang"],
    ["id" => 3372, "id_provinsi" => 33, "kabupaten" => "Kota Surakarta"],
    ["id" => 3373, "id_provinsi" => 33, "kabupaten" => "Kota Salatiga"],
    ["id" => 3374, "id_provinsi" => 33, "kabupaten" => "Kota Semarang"],
    ["id" => 3375, "id_provinsi" => 33, "kabupaten" => "Kota Pekalongan"],
    ["id" => 3376, "id_provinsi" => 33, "kabupaten" => "Kota Tegal"],
    ["id" => 3401, "id_provinsi" => 34, "kabupaten" => "Kab. Kulon Progo"],
    ["id" => 3402, "id_provinsi" => 34, "kabupaten" => "Kab. Bantul"],
    ["id" => 3403, "id_provinsi" => 34, "kabupaten" => "Kab. Gunung Kidul"],
    ["id" => 3404, "id_provinsi" => 34, "kabupaten" => "Kab. Sleman"],
    ["id" => 3471, "id_provinsi" => 34, "kabupaten" => "Kota Yogyakarta"],
    ["id" => 3501, "id_provinsi" => 35, "kabupaten" => "Kab. Pacitan"],
    ["id" => 3502, "id_provinsi" => 35, "kabupaten" => "Kab. Ponorogo"],
    ["id" => 3503, "id_provinsi" => 35, "kabupaten" => "Kab. Trenggalek"],
    ["id" => 3504, "id_provinsi" => 35, "kabupaten" => "Kab. Tulungagung"],
    ["id" => 3505, "id_provinsi" => 35, "kabupaten" => "Kab. Blitar"],
    ["id" => 3506, "id_provinsi" => 35, "kabupaten" => "Kab. Kediri"],
    ["id" => 3507, "id_provinsi" => 35, "kabupaten" => "Kab. Malang"],
    ["id" => 3508, "id_provinsi" => 35, "kabupaten" => "Kab. Lumajang"],
    ["id" => 3509, "id_provinsi" => 35, "kabupaten" => "Kab. Jember"],
    ["id" => 3510, "id_provinsi" => 35, "kabupaten" => "Kab. Banyuwangi"],
    ["id" => 3511, "id_provinsi" => 35, "kabupaten" => "Kab. Bondowoso"],
    ["id" => 3512, "id_provinsi" => 35, "kabupaten" => "Kab. Situbondo"],
    ["id" => 3513, "id_provinsi" => 35, "kabupaten" => "Kab. Probolinggo"],
    ["id" => 3514, "id_provinsi" => 35, "kabupaten" => "Kab. Pasuruan"],
    ["id" => 3515, "id_provinsi" => 35, "kabupaten" => "Kab. Sidoarjo"],
    ["id" => 3516, "id_provinsi" => 35, "kabupaten" => "Kab. Mojokerto"],
    ["id" => 3517, "id_provinsi" => 35, "kabupaten" => "Kab. Jombang"],
    ["id" => 3518, "id_provinsi" => 35, "kabupaten" => "Kab. Nganjuk"],
    ["id" => 3519, "id_provinsi" => 35, "kabupaten" => "Kab. Madiun"],
    ["id" => 3520, "id_provinsi" => 35, "kabupaten" => "Kab. Magetan"],
    ["id" => 3521, "id_provinsi" => 35, "kabupaten" => "Kab. Ngawi"],
    ["id" => 3522, "id_provinsi" => 35, "kabupaten" => "Kab. Bojonegoro"],
    ["id" => 3523, "id_provinsi" => 35, "kabupaten" => "Kab. Tuban"],
    ["id" => 3524, "id_provinsi" => 35, "kabupaten" => "Kab. Lamongan"],
    ["id" => 3525, "id_provinsi" => 35, "kabupaten" => "Kab. Gresik"],
    ["id" => 3526, "id_provinsi" => 35, "kabupaten" => "Kab. Bangkalan"],
    ["id" => 3527, "id_provinsi" => 35, "kabupaten" => "Kab. Sampang"],
    ["id" => 3528, "id_provinsi" => 35, "kabupaten" => "Kab. Pamekasan"],
    ["id" => 3529, "id_provinsi" => 35, "kabupaten" => "Kab. Sumenep"],
    ["id" => 3571, "id_provinsi" => 35, "kabupaten" => "Kota Kediri"],
    ["id" => 3572, "id_provinsi" => 35, "kabupaten" => "Kota Blitar"],
    ["id" => 3573, "id_provinsi" => 35, "kabupaten" => "Kota Malang"],
    ["id" => 3574, "id_provinsi" => 35, "kabupaten" => "Kota Probolinggo"],
    ["id" => 3575, "id_provinsi" => 35, "kabupaten" => "Kota Pasuruan"],
    ["id" => 3576, "id_provinsi" => 35, "kabupaten" => "Kota Mojokerto"],
    ["id" => 3577, "id_provinsi" => 35, "kabupaten" => "Kota Madiun"],
    ["id" => 3578, "id_provinsi" => 35, "kabupaten" => "Kota Surabaya"],
    ["id" => 3579, "id_provinsi" => 35, "kabupaten" => "Kota Batu"],
    ["id" => 3601, "id_provinsi" => 36, "kabupaten" => "Kab. Pandeglang"],
    ["id" => 3602, "id_provinsi" => 36, "kabupaten" => "Kab. Lebak"],
    ["id" => 3603, "id_provinsi" => 36, "kabupaten" => "Kab. Tangerang"],
    ["id" => 3604, "id_provinsi" => 36, "kabupaten" => "Kab. Serang"],
    ["id" => 3671, "id_provinsi" => 36, "kabupaten" => "Kota Tangerang"],
    ["id" => 3672, "id_provinsi" => 36, "kabupaten" => "Kota Cilegon"],
    ["id" => 3673, "id_provinsi" => 36, "kabupaten" => "Kota Serang"],
    [
        "id" => 3674,
        "id_provinsi" => 36,
        "kabupaten" => "Kota Tangerang Selatan",
    ],
    ["id" => 5101, "id_provinsi" => 51, "kabupaten" => "Kab. Jembrana"],
    ["id" => 5102, "id_provinsi" => 51, "kabupaten" => "Kab. Tabanan"],
    ["id" => 5103, "id_provinsi" => 51, "kabupaten" => "Kab. Badung"],
    ["id" => 5104, "id_provinsi" => 51, "kabupaten" => "Kab. Gianyar"],
    ["id" => 5105, "id_provinsi" => 51, "kabupaten" => "Kab. Klungkung"],
    ["id" => 5106, "id_provinsi" => 51, "kabupaten" => "Kab. Bangli"],
    ["id" => 5107, "id_provinsi" => 51, "kabupaten" => "Kab. Karang Asem"],
    ["id" => 5108, "id_provinsi" => 51, "kabupaten" => "Kab. Buleleng"],
    ["id" => 5171, "id_provinsi" => 51, "kabupaten" => "Kota Denpasar"],
    ["id" => 5201, "id_provinsi" => 52, "kabupaten" => "Kab. Lombok Barat"],
    ["id" => 5202, "id_provinsi" => 52, "kabupaten" => "Kab. Lombok Tengah"],
    ["id" => 5203, "id_provinsi" => 52, "kabupaten" => "Kab. Lombok Timur"],
    ["id" => 5204, "id_provinsi" => 52, "kabupaten" => "Kab. Sumbawa"],
    ["id" => 5205, "id_provinsi" => 52, "kabupaten" => "Kab. Dompu"],
    ["id" => 5206, "id_provinsi" => 52, "kabupaten" => "Kab. Bima"],
    ["id" => 5207, "id_provinsi" => 52, "kabupaten" => "Kab. Sumbawa Barat"],
    ["id" => 5208, "id_provinsi" => 52, "kabupaten" => "Kab. Lombok Utara"],
    ["id" => 5271, "id_provinsi" => 52, "kabupaten" => "Kota Mataram"],
    ["id" => 5272, "id_provinsi" => 52, "kabupaten" => "Kota Bima"],
    ["id" => 5301, "id_provinsi" => 53, "kabupaten" => "Kab. Sumba Barat"],
    ["id" => 5302, "id_provinsi" => 53, "kabupaten" => "Kab. Sumba Timur"],
    ["id" => 5303, "id_provinsi" => 53, "kabupaten" => "Kab. Kupang"],
    [
        "id" => 5304,
        "id_provinsi" => 53,
        "kabupaten" => "Kab. Timor Tengah Selatan",
    ],
    [
        "id" => 5305,
        "id_provinsi" => 53,
        "kabupaten" => "Kab. Timor Tengah Utara",
    ],
    ["id" => 5306, "id_provinsi" => 53, "kabupaten" => "Kab. Belu"],
    ["id" => 5307, "id_provinsi" => 53, "kabupaten" => "Kab. Alor"],
    ["id" => 5308, "id_provinsi" => 53, "kabupaten" => "Kab. Lembata"],
    ["id" => 5309, "id_provinsi" => 53, "kabupaten" => "Kab. Flores Timur"],
    ["id" => 5310, "id_provinsi" => 53, "kabupaten" => "Kab. Sikka"],
    ["id" => 5311, "id_provinsi" => 53, "kabupaten" => "Kab. Ende"],
    ["id" => 5312, "id_provinsi" => 53, "kabupaten" => "Kab. Ngada"],
    ["id" => 5313, "id_provinsi" => 53, "kabupaten" => "Kab. Manggarai"],
    ["id" => 5314, "id_provinsi" => 53, "kabupaten" => "Kab. Rote Ndao"],
    ["id" => 5315, "id_provinsi" => 53, "kabupaten" => "Kab. Manggarai Barat"],
    ["id" => 5316, "id_provinsi" => 53, "kabupaten" => "Kab. Sumba Tengah"],
    ["id" => 5317, "id_provinsi" => 53, "kabupaten" => "Kab. Sumba Barat Daya"],
    ["id" => 5318, "id_provinsi" => 53, "kabupaten" => "Kab. Nagekeo"],
    ["id" => 5319, "id_provinsi" => 53, "kabupaten" => "Kab. Manggarai Timur"],
    ["id" => 5320, "id_provinsi" => 53, "kabupaten" => "Kab. Sabu Raijua"],
    ["id" => 5371, "id_provinsi" => 53, "kabupaten" => "Kota Kupang"],
    ["id" => 6101, "id_provinsi" => 61, "kabupaten" => "Kab. Sambas"],
    ["id" => 6102, "id_provinsi" => 61, "kabupaten" => "Kab. Bengkayang"],
    ["id" => 6103, "id_provinsi" => 61, "kabupaten" => "Kab. Landak"],
    ["id" => 6104, "id_provinsi" => 61, "kabupaten" => "Kab. Pontianak"],
    ["id" => 6105, "id_provinsi" => 61, "kabupaten" => "Kab. Sanggau"],
    ["id" => 6106, "id_provinsi" => 61, "kabupaten" => "Kab. Ketapang"],
    ["id" => 6107, "id_provinsi" => 61, "kabupaten" => "Kab. Sintang"],
    ["id" => 6108, "id_provinsi" => 61, "kabupaten" => "Kab. Kapuas Hulu"],
    ["id" => 6109, "id_provinsi" => 61, "kabupaten" => "Kab. Sekadau"],
    ["id" => 6110, "id_provinsi" => 61, "kabupaten" => "Kab. Melawi"],
    ["id" => 6111, "id_provinsi" => 61, "kabupaten" => "Kab. Kayong Utara"],
    ["id" => 6112, "id_provinsi" => 61, "kabupaten" => "Kab. Kubu Raya"],
    ["id" => 6171, "id_provinsi" => 61, "kabupaten" => "Kota Pontianak"],
    ["id" => 6172, "id_provinsi" => 61, "kabupaten" => "Kota Singkawang"],
    [
        "id" => 6201,
        "id_provinsi" => 62,
        "kabupaten" => "Kab. Kotawaringin Barat",
    ],
    [
        "id" => 6202,
        "id_provinsi" => 62,
        "kabupaten" => "Kab. Kotawaringin Timur",
    ],
    ["id" => 6203, "id_provinsi" => 62, "kabupaten" => "Kab. Kapuas"],
    ["id" => 6204, "id_provinsi" => 62, "kabupaten" => "Kab. Barito Selatan"],
    ["id" => 6205, "id_provinsi" => 62, "kabupaten" => "Kab. Barito Utara"],
    ["id" => 6206, "id_provinsi" => 62, "kabupaten" => "Kab. Sukamara"],
    ["id" => 6207, "id_provinsi" => 62, "kabupaten" => "Kab. Lamandau"],
    ["id" => 6208, "id_provinsi" => 62, "kabupaten" => "Kab. Seruyan"],
    ["id" => 6209, "id_provinsi" => 62, "kabupaten" => "Kab. Katingan"],
    ["id" => 6210, "id_provinsi" => 62, "kabupaten" => "Kab. Pulang Pisau"],
    ["id" => 6211, "id_provinsi" => 62, "kabupaten" => "Kab. Gunung Mas"],
    ["id" => 6212, "id_provinsi" => 62, "kabupaten" => "Kab. Barito Timur"],
    ["id" => 6213, "id_provinsi" => 62, "kabupaten" => "Kab. Murung Raya"],
    ["id" => 6271, "id_provinsi" => 62, "kabupaten" => "Kota Palangka Raya"],
    ["id" => 6301, "id_provinsi" => 63, "kabupaten" => "Kab. Tanah Laut"],
    ["id" => 6302, "id_provinsi" => 63, "kabupaten" => "Kab. Kota Baru"],
    ["id" => 6303, "id_provinsi" => 63, "kabupaten" => "Kab. Banjar"],
    ["id" => 6304, "id_provinsi" => 63, "kabupaten" => "Kab. Barito Kuala"],
    ["id" => 6305, "id_provinsi" => 63, "kabupaten" => "Kab. Tapin"],
    [
        "id" => 6306,
        "id_provinsi" => 63,
        "kabupaten" => "Kab. Hulu Sungai Selatan",
    ],
    [
        "id" => 6307,
        "id_provinsi" => 63,
        "kabupaten" => "Kab. Hulu Sungai Tengah",
    ],
    [
        "id" => 6308,
        "id_provinsi" => 63,
        "kabupaten" => "Kab. Hulu Sungai Utara",
    ],
    ["id" => 6309, "id_provinsi" => 63, "kabupaten" => "Kab. Tabalong"],
    ["id" => 6310, "id_provinsi" => 63, "kabupaten" => "Kab. Tanah Bumbu"],
    ["id" => 6311, "id_provinsi" => 63, "kabupaten" => "Kab. Balangan"],
    ["id" => 6371, "id_provinsi" => 63, "kabupaten" => "Kota Banjarmasin"],
    ["id" => 6372, "id_provinsi" => 63, "kabupaten" => "Kota Banjar Baru"],
    ["id" => 6401, "id_provinsi" => 64, "kabupaten" => "Kab. Paser"],
    ["id" => 6402, "id_provinsi" => 64, "kabupaten" => "Kab. Kutai Barat"],
    [
        "id" => 6403,
        "id_provinsi" => 64,
        "kabupaten" => "Kab. Kutai Kartanegara",
    ],
    ["id" => 6404, "id_provinsi" => 64, "kabupaten" => "Kab. Kutai Timur"],
    ["id" => 6405, "id_provinsi" => 64, "kabupaten" => "Kab. Berau"],
    [
        "id" => 6409,
        "id_provinsi" => 64,
        "kabupaten" => "Kab. Penajam Paser Utara",
    ],
    ["id" => 6471, "id_provinsi" => 64, "kabupaten" => "Kota Balikpapan"],
    ["id" => 6472, "id_provinsi" => 64, "kabupaten" => "Kota Samarinda"],
    ["id" => 6474, "id_provinsi" => 64, "kabupaten" => "Kota Bontang"],
    ["id" => 6501, "id_provinsi" => 65, "kabupaten" => "Kab. Malinau"],
    ["id" => 6502, "id_provinsi" => 65, "kabupaten" => "Kab. Bulungan"],
    ["id" => 6503, "id_provinsi" => 65, "kabupaten" => "Kab. Tana Tidung"],
    ["id" => 6504, "id_provinsi" => 65, "kabupaten" => "Kab. Nunukan"],
    ["id" => 6571, "id_provinsi" => 65, "kabupaten" => "Kota Tarakan"],
    [
        "id" => 7101,
        "id_provinsi" => 71,
        "kabupaten" => "Kab. Bolaang Mongondow",
    ],
    ["id" => 7102, "id_provinsi" => 71, "kabupaten" => "Kab. Minahasa"],
    [
        "id" => 7103,
        "id_provinsi" => 71,
        "kabupaten" => "Kab. Kepulauan Sangihe",
    ],
    ["id" => 7104, "id_provinsi" => 71, "kabupaten" => "Kab. Kepulauan Talaud"],
    ["id" => 7105, "id_provinsi" => 71, "kabupaten" => "Kab. Minahasa Selatan"],
    ["id" => 7106, "id_provinsi" => 71, "kabupaten" => "Kab. Minahasa Utara"],
    [
        "id" => 7107,
        "id_provinsi" => 71,
        "kabupaten" => "Kab. Bolaang Mongondow Utara",
    ],
    [
        "id" => 7108,
        "id_provinsi" => 71,
        "kabupaten" => "Kab. Siau Tagulandang Biaro",
    ],
    [
        "id" => 7109,
        "id_provinsi" => 71,
        "kabupaten" => "Kab. Minahasa Tenggara",
    ],
    [
        "id" => 7110,
        "id_provinsi" => 71,
        "kabupaten" => "Kab. Bolaang Mongondow Selatan",
    ],
    [
        "id" => 7111,
        "id_provinsi" => 71,
        "kabupaten" => "Kab. Bolaang Mongondow Timur",
    ],
    ["id" => 7171, "id_provinsi" => 71, "kabupaten" => "Kota Manado"],
    ["id" => 7172, "id_provinsi" => 71, "kabupaten" => "Kota Bitung"],
    ["id" => 7173, "id_provinsi" => 71, "kabupaten" => "Kota Tomohon"],
    ["id" => 7174, "id_provinsi" => 71, "kabupaten" => "Kota Kotamobagu"],
    [
        "id" => 7201,
        "id_provinsi" => 72,
        "kabupaten" => "Kab. Banggai Kepulauan",
    ],
    ["id" => 7202, "id_provinsi" => 72, "kabupaten" => "Kab. Banggai"],
    ["id" => 7203, "id_provinsi" => 72, "kabupaten" => "Kab. Morowali"],
    ["id" => 7204, "id_provinsi" => 72, "kabupaten" => "Kab. Poso"],
    ["id" => 7205, "id_provinsi" => 72, "kabupaten" => "Kab. Donggala"],
    ["id" => 7206, "id_provinsi" => 72, "kabupaten" => "Kab. Toli-toli"],
    ["id" => 7207, "id_provinsi" => 72, "kabupaten" => "Kab. Buol"],
    ["id" => 7208, "id_provinsi" => 72, "kabupaten" => "Kab. Parigi Moutong"],
    ["id" => 7209, "id_provinsi" => 72, "kabupaten" => "Kab. Tojo Una-una"],
    ["id" => 7210, "id_provinsi" => 72, "kabupaten" => "Kab. Sigi"],
    ["id" => 7271, "id_provinsi" => 72, "kabupaten" => "Kota Palu"],
    [
        "id" => 7301,
        "id_provinsi" => 73,
        "kabupaten" => "Kab. Kepulauan Selayar",
    ],
    ["id" => 7302, "id_provinsi" => 73, "kabupaten" => "Kab. Bulukumba"],
    ["id" => 7303, "id_provinsi" => 73, "kabupaten" => "Kab. Bantaeng"],
    ["id" => 7304, "id_provinsi" => 73, "kabupaten" => "Kab. Jeneponto"],
    ["id" => 7305, "id_provinsi" => 73, "kabupaten" => "Kab. Takalar"],
    ["id" => 7306, "id_provinsi" => 73, "kabupaten" => "Kab. Gowa"],
    ["id" => 7307, "id_provinsi" => 73, "kabupaten" => "Kab. Sinjai"],
    ["id" => 7308, "id_provinsi" => 73, "kabupaten" => "Kab. Maros"],
    [
        "id" => 7309,
        "id_provinsi" => 73,
        "kabupaten" => "Kab. Pangkajene Dan Kepulauan",
    ],
    ["id" => 7310, "id_provinsi" => 73, "kabupaten" => "Kab. Barru"],
    ["id" => 7311, "id_provinsi" => 73, "kabupaten" => "Kab. Bone"],
    ["id" => 7312, "id_provinsi" => 73, "kabupaten" => "Kab. Soppeng"],
    ["id" => 7313, "id_provinsi" => 73, "kabupaten" => "Kab. Wajo"],
    [
        "id" => 7314,
        "id_provinsi" => 73,
        "kabupaten" => "Kab. Sidenreng Rappang",
    ],
    ["id" => 7315, "id_provinsi" => 73, "kabupaten" => "Kab. Pinrang"],
    ["id" => 7316, "id_provinsi" => 73, "kabupaten" => "Kab. Enrekang"],
    ["id" => 7317, "id_provinsi" => 73, "kabupaten" => "Kab. Luwu"],
    ["id" => 7318, "id_provinsi" => 73, "kabupaten" => "Kab. Tana Toraja"],
    ["id" => 7322, "id_provinsi" => 73, "kabupaten" => "Kab. Luwu Utara"],
    ["id" => 7325, "id_provinsi" => 73, "kabupaten" => "Kab. Luwu Timur"],
    ["id" => 7326, "id_provinsi" => 73, "kabupaten" => "Kab. Toraja Utara"],
    ["id" => 7371, "id_provinsi" => 73, "kabupaten" => "Kota Makassar"],
    ["id" => 7372, "id_provinsi" => 73, "kabupaten" => "Kota Parepare"],
    ["id" => 7373, "id_provinsi" => 73, "kabupaten" => "Kota Palopo"],
    ["id" => 7401, "id_provinsi" => 74, "kabupaten" => "Kab. Buton"],
    ["id" => 7402, "id_provinsi" => 74, "kabupaten" => "Kab. Muna"],
    ["id" => 7403, "id_provinsi" => 74, "kabupaten" => "Kab. Konawe"],
    ["id" => 7404, "id_provinsi" => 74, "kabupaten" => "Kab. Kolaka"],
    ["id" => 7405, "id_provinsi" => 74, "kabupaten" => "Kab. Konawe Selatan"],
    ["id" => 7406, "id_provinsi" => 74, "kabupaten" => "Kab. Bombana"],
    ["id" => 7407, "id_provinsi" => 74, "kabupaten" => "Kab. Wakatobi"],
    ["id" => 7408, "id_provinsi" => 74, "kabupaten" => "Kab. Kolaka Utara"],
    ["id" => 7409, "id_provinsi" => 74, "kabupaten" => "Kab. Buton Utara"],
    ["id" => 7410, "id_provinsi" => 74, "kabupaten" => "Kab. Konawe Utara"],
    ["id" => 7471, "id_provinsi" => 74, "kabupaten" => "Kota Kendari"],
    ["id" => 7472, "id_provinsi" => 74, "kabupaten" => "Kota Baubau"],
    ["id" => 7501, "id_provinsi" => 75, "kabupaten" => "Kab. Boalemo"],
    ["id" => 7502, "id_provinsi" => 75, "kabupaten" => "Kab. Gorontalo"],
    ["id" => 7503, "id_provinsi" => 75, "kabupaten" => "Kab. Pohuwato"],
    ["id" => 7504, "id_provinsi" => 75, "kabupaten" => "Kab. Bone Bolango"],
    ["id" => 7505, "id_provinsi" => 75, "kabupaten" => "Kab. Gorontalo Utara"],
    ["id" => 7571, "id_provinsi" => 75, "kabupaten" => "Kota Gorontalo"],
    ["id" => 7601, "id_provinsi" => 76, "kabupaten" => "Kab. Majene"],
    ["id" => 7602, "id_provinsi" => 76, "kabupaten" => "Kab. Polewali Mandar"],
    ["id" => 7603, "id_provinsi" => 76, "kabupaten" => "Kab. Mamasa"],
    ["id" => 7604, "id_provinsi" => 76, "kabupaten" => "Kab. Mamuju"],
    ["id" => 7605, "id_provinsi" => 76, "kabupaten" => "Kab. Mamuju Utara"],
    [
        "id" => 8101,
        "id_provinsi" => 81,
        "kabupaten" => "Kab. Maluku Tenggara Barat",
    ],
    ["id" => 8102, "id_provinsi" => 81, "kabupaten" => "Kab. Maluku Tenggara"],
    ["id" => 8103, "id_provinsi" => 81, "kabupaten" => "Kab. Maluku Tengah"],
    ["id" => 8104, "id_provinsi" => 81, "kabupaten" => "Kab. Buru"],
    ["id" => 8105, "id_provinsi" => 81, "kabupaten" => "Kab. Kepulauan Aru"],
    [
        "id" => 8106,
        "id_provinsi" => 81,
        "kabupaten" => "Kab. Seram Bagian Barat",
    ],
    [
        "id" => 8107,
        "id_provinsi" => 81,
        "kabupaten" => "Kab. Seram Bagian Timur",
    ],
    [
        "id" => 8108,
        "id_provinsi" => 81,
        "kabupaten" => "Kab. Maluku Barat Daya",
    ],
    ["id" => 8109, "id_provinsi" => 81, "kabupaten" => "Kab. Buru Selatan"],
    ["id" => 8171, "id_provinsi" => 81, "kabupaten" => "Kota Ambon"],
    ["id" => 8172, "id_provinsi" => 81, "kabupaten" => "Kota Tual"],
    ["id" => 8201, "id_provinsi" => 82, "kabupaten" => "Kab. Halmahera Barat"],
    ["id" => 8202, "id_provinsi" => 82, "kabupaten" => "Kab. Halmahera Tengah"],
    ["id" => 8203, "id_provinsi" => 82, "kabupaten" => "Kab. Kepulauan Sula"],
    [
        "id" => 8204,
        "id_provinsi" => 82,
        "kabupaten" => "Kab. Halmahera Selatan",
    ],
    ["id" => 8205, "id_provinsi" => 82, "kabupaten" => "Kab. Halmahera Utara"],
    ["id" => 8206, "id_provinsi" => 82, "kabupaten" => "Kab. Halmahera Timur"],
    ["id" => 8207, "id_provinsi" => 82, "kabupaten" => "Kab. Pulau Morotai"],
    ["id" => 8271, "id_provinsi" => 82, "kabupaten" => "Kota Ternate"],
    ["id" => 8272, "id_provinsi" => 82, "kabupaten" => "Kota Tidore Kepulauan"],
    ["id" => 9101, "id_provinsi" => 91, "kabupaten" => "Kab. Fakfak"],
    ["id" => 9102, "id_provinsi" => 91, "kabupaten" => "Kab. Kaimana"],
    ["id" => 9103, "id_provinsi" => 91, "kabupaten" => "Kab. Teluk Wondama"],
    ["id" => 9104, "id_provinsi" => 91, "kabupaten" => "Kab. Teluk Bintuni"],
    ["id" => 9105, "id_provinsi" => 91, "kabupaten" => "Kab. Manokwari"],
    ["id" => 9106, "id_provinsi" => 91, "kabupaten" => "Kab. Sorong Selatan"],
    ["id" => 9107, "id_provinsi" => 91, "kabupaten" => "Kab. Sorong"],
    ["id" => 9108, "id_provinsi" => 91, "kabupaten" => "Kab. Raja Ampat"],
    ["id" => 9109, "id_provinsi" => 91, "kabupaten" => "Kab. Tambrauw"],
    ["id" => 9110, "id_provinsi" => 91, "kabupaten" => "Kab. Maybrat"],
    ["id" => 9171, "id_provinsi" => 91, "kabupaten" => "Kota Sorong"],
    ["id" => 9401, "id_provinsi" => 94, "kabupaten" => "Kab. Merauke"],
    ["id" => 9402, "id_provinsi" => 94, "kabupaten" => "Kab. Jayawijaya"],
    ["id" => 9403, "id_provinsi" => 94, "kabupaten" => "Kab. Jayapura"],
    ["id" => 9404, "id_provinsi" => 94, "kabupaten" => "Kab. Nabire"],
    ["id" => 9408, "id_provinsi" => 94, "kabupaten" => "Kab. Kepulauan Yapen"],
    ["id" => 9409, "id_provinsi" => 94, "kabupaten" => "Kab. Biak Numfor"],
    ["id" => 9410, "id_provinsi" => 94, "kabupaten" => "Kab. Paniai"],
    ["id" => 9411, "id_provinsi" => 94, "kabupaten" => "Kab. Puncak Jaya"],
    ["id" => 9412, "id_provinsi" => 94, "kabupaten" => "Kab. Mimika"],
    ["id" => 9413, "id_provinsi" => 94, "kabupaten" => "Kab. Boven Digoel"],
    ["id" => 9414, "id_provinsi" => 94, "kabupaten" => "Kab. Mappi"],
    ["id" => 9415, "id_provinsi" => 94, "kabupaten" => "Kab. Asmat"],
    ["id" => 9416, "id_provinsi" => 94, "kabupaten" => "Kab. Yahukimo"],
    [
        "id" => 9417,
        "id_provinsi" => 94,
        "kabupaten" => "Kab. Pegunungan Bintang",
    ],
    ["id" => 9418, "id_provinsi" => 94, "kabupaten" => "Kab. Tolikara"],
    ["id" => 9419, "id_provinsi" => 94, "kabupaten" => "Kab. Sarmi"],
    ["id" => 9420, "id_provinsi" => 94, "kabupaten" => "Kab. Keerom"],
    ["id" => 9426, "id_provinsi" => 94, "kabupaten" => "Kab. Waropen"],
    ["id" => 9427, "id_provinsi" => 94, "kabupaten" => "Kab. Supiori"],
    ["id" => 9428, "id_provinsi" => 94, "kabupaten" => "Kab. Mamberamo Raya"],
    ["id" => 9429, "id_provinsi" => 94, "kabupaten" => "Kab. Nduga"],
    ["id" => 9430, "id_provinsi" => 94, "kabupaten" => "Kab. Lanny Jaya"],
    ["id" => 9431, "id_provinsi" => 94, "kabupaten" => "Kab. Mamberamo Tengah"],
    ["id" => 9432, "id_provinsi" => 94, "kabupaten" => "Kab. Yalimo"],
    ["id" => 9433, "id_provinsi" => 94, "kabupaten" => "Kab. Puncak"],
    ["id" => 9434, "id_provinsi" => 94, "kabupaten" => "Kab. Dogiyai"],
    ["id" => 9435, "id_provinsi" => 94, "kabupaten" => "Kab. Intan Jaya"],
    ["id" => 9436, "id_provinsi" => 94, "kabupaten" => "Kab. Deiyai"],
    ["id" => 9471, "id_provinsi" => 94, "kabupaten" => "Kota Jayapura"],
];

        // $this->command->getOutput()->progressStart(count($data));
        $this->generate($data);
        // $this->command->getOutput()->progressFinish();
    }

    public function generate($data)
    {
        \DB::unprepared('SET IDENTITY_INSERT sys_kota ON');
        foreach ($data as $key => $item) {
            Kota::create([
                'id' =>  $item['id'],
                'provinsi_id' =>  $item['id_provinsi'],
                'nama' => $item['kabupaten']
            ]);
            // $this->command->getOutput()->progressAdvance();
        }
        // \DB::unprepared('SET IDENTITY_INSERT sys_kota OFF');
    }
}
