<style>
    /* #### Generated By: http://www.cufonfonts.com #### */
    @font-face {
        font-family: 'Myriad Pro Regular';
        font-style: normal;
        font-weight: normal;
        src: url("../storage/fonts/MYRIADPRO-REGULAR.ttf") format('truetype');
        /* src: local('Myriad Pro Regular'), url('/assets/fonts/myriadpro/MYRIADPRO-REGULAR.woff') format('woff'); */
    }

    @font-face {
        font-family: 'Myriad Pro Condensed';
        font-style: normal;
        font-weight: normal;
        src: url("../storage/fonts/MYRIADPRO-BOLDCOND.ttf") format('truetype');
        /* src: local('Myriad Pro Condensed'), url('/assets/fonts/myriadpro/MYRIADPRO-COND.woff') format('woff'); */
    }

    @font-face {
        font-family: 'Myriad Pro Condensed Italic';
        font-style: normal;
        font-weight: normal;
        src: url("../storage/fonts/MYRIADPRO-CONDIT.ttf") format('truetype');
        /* src: local('Myriad Pro Condensed Italic'), url('/assets/fonts/myriadpro/MYRIADPRO-CONDIT.woff') format('woff'); */
    }

    @font-face {
        font-family: 'Myriad Pro Light';
        font-style: normal;
        font-weight: normal;
        src: url("../storage/fonts/MYRIADPRO-REGULAR.ttf") format('truetype');
        /* src: local('Myriad Pro Light'), url('/assets/fonts/myriadpro/MyriadPro-Light.woff') format('woff'); */
    }

    @font-face {
        font-family: 'Myriad Pro Semibold';
        font-style: normal;
        font-weight: normal;
        src: url("../storage/fonts/MYRIADPRO-BOLD.ttf") format('truetype');
        /* src: local('Myriad Pro Semibold'), url('/assets/fonts/myriadpro/MYRIADPRO-SEMIBOLD.woff') format('woff'); */
    }

    @font-face {
        font-family: 'Myriad Pro Semibold Italic';
        font-style: normal;
        font-weight: normal;
        src: local('Myriad Pro Semibold Italic'), url('/assets/fonts/myriadpro/MYRIADPRO-SEMIBOLDIT.woff') format('woff');
    }

    @font-face {
        font-family: 'Myriad Pro Bold Condensed';
        font-style: normal;
        font-weight: normal;
        src: local('Myriad Pro Bold Condensed'), url('/assets/fonts/myriadpro/MYRIADPRO-BOLDCOND.woff') format('woff');
    }

    @font-face {
        font-family: 'Myriad Pro Bold';
        font-style: normal;
        font-weight: normal;
        src: url("../storage/fonts/MYRIADPRO-BOLD.ttf") format('truetype');
        /* src: local('Myriad Pro Bold'), url('/assets/fonts/myriadpro/MYRIADPRO-BOLD.woff') format('woff'); */
    }

    @font-face {
        font-family: 'Myriad Pro Bold Italic';
        font-style: normal;
        font-weight: normal;
        src: local('Myriad Pro Bold Italic'), url('/assets/fonts/myriadpro/MYRIADPRO-BOLDIT.woff') format('woff');
    }

    @font-face {
        font-family: 'Myriad Pro Bold Condensed Italic';
        font-style: normal;
        font-weight: normal;
        src: local('Myriad Pro Bold Condensed Italic'), url('/assets/fonts/myriadpro/MYRIADPRO-BOLDCONDIT.woff') format('woff');
    }

    * {
        box-sizing: border-box;
        font-family: "Myriad Pro Regular", Arial, sans-serif;
    }

    /** Define the margins of your page **/
    @page {
        margin: 1cm 1.3cm 1.5cm;
    }

    body {
        /* margin-top: 2cm; */
        /* padding-top: 2cm; */
        font-family: "Myriad Pro Regular", Arial, sans-serif;
        font-size: 12pt;
    }

    header {
        /* position: fixed; */
        top: 0px;
        left: 0;
        right: 0;
        /*margin-left: 10mm;*/
        /*margin-right: 5mm;*/
        /*line-height: 35px;*/
    }

    footer {
        position: fixed;
        bottom: -50px;
        left: 0px;
        right: 0;
        height: 50px;
        /* line-height: 35px; */
    }

    .pagenum:before {
        content: counter(page);
        content: counter(page, decimal);
    }

    table {
        width: 100%;
        border: 1pt solid black;
        border-collapse: collapse;
    }

    tr th,
    tr td {
        border-bottom: 1pt solid black;
        border: 1pt solid black;
        border-right: 1pt solid black;
    }

    ul,
    ol {
        margin: 0;
        padding-left: 20px;
    }

    .table-data {
        height: 44px;
        background-repeat: no-repeat;
        /*background-position: center center;*/
        border: 1px solid;
        /*text-align: justify;*/
        /*background-color: #ffffff;*/
        font-weight: normal;
        /*color: #555555;*/
        /*padding: 11px 5px 11px 5px;*/
        vertical-align: middle;
    }

    .table-data tr th,
    .table-data tr td {
        padding: 5px 8px;
    }

    .table-data tr td {
        vertical-align: top;
    }

    table.table-borderless tr td {
        border: none;
    }

    table.table-bordered tr td {
        border: 1px solid #333;
    }

    .page-break: {
        page-break-inside: always;
    }

    .nowrap {
        white-space: nowrap;
    }

    .text-center {
        text-align: center;
    }
</style>
